
dist: xenial
language: go
go_import_path: kubevirt.io/node-maintenance-operator
go: "1.13.5"

services:
- docker

install: true

script:
- make check
- make container-build

before_deploy:
- echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" quay.io --password-stdin

deploy:
- provider: script
  script: make container-build container-push
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: make manifests container-build container-push IMAGE_TAG=$TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  on:
    tags: true
    repo: kubevirt/node-maintenance-operator
  api_key:
    secure: whS1MO7NoOY7HDTGhRWwi+YY391g46PiDUMQNxaaeGaMkvpCjw97j4QHk1MS7k59Yx1C8k7Cn27CkM0/6vy3jAkaSXY8WCODWqgV1PJcC8ruRQMHuSIpCKNKWbzXksl46jYz2rechnPFGWcTET3/t192/Pzdl07uLfY/GrTwJ1Xs4vH5NRxKcqJmDNiRBysqHxvEx4dz8ozLLXFjdR/XPinUA+A5dtbqbuBb89k4zvBaziLl1p75Z5G/Sffq5pRDj/XXi18mMYmal2lS0vo1KreZEGaz5N670U15J7KzgUyMr8TUgAj18gth6y4eEaIIp3eW2uNDwf38D5UA6hcCVHAfbrttD/EER5QWitI8IQ5UhuL1muQNCeJg+SYRGcS8c6T3dgZYqxEXsKRwoJ/4OQhi1FohsR6abQvK5nMPKzuKHhlZ2bGL+a4CoxDacnra2pF+FASaLdzmYxVtWdaoQuutc/ssM1fhlTw44VmeVs/d9VWD3lk0zx2QuNmd4iLD6NfVPaRFeiYyITOB8bR/a5e+1M0IKYd14qJ6mp3UKgOq8oVef97Y0ky4qduANRlTh8Uf3OxNrJ81KfGb9csZ6PQMqEAkW5Qb+tqg14WsrYR1TOiQeBtpDV0Sd44c9akKgyynOrG/ejHD2um3IuuFxtB02Zx39YvoxBgSrpO+/2M=
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - _out/*

