#!/bin/bash

CMD=/usr/bin/oc
STYLE=json

COLLECTION_PATH="/must-gather"

show_header() {
	local title="$1"

	echo "*** ${title} ***"
	echo ""
}

run_command() {
    local cmd="$1"
    local ofile="$2"

	echo "Command: $cmd"
    if [[ $ofile == "" ]]; then
        $cmd
    else
        $cmd | tee $ofile
    fi
	echo ""
}

get_namespace() {
	local deployment_name="$1"
	$CMD get deployments --all-namespaces | /usr/bin/grep ${deployment_name} | /usr/bin/awk '{ print $1 }'
}

show_operator_info() {
	local operator_short_name="$1"
	local crd_name="$2"
	local title="$3"

	show_header "${title} crd's"

	run_command "${CMD} get crds ${crd_name} -o wide"
    run_command "${CMD} get crds ${crd_name} -o ${STYLE}" "${COLLECTION_PATH}/crd.yaml"

    show_header "${title} active cr objects"

    run_command "${CMD} oc get NodeMaintenance -o ${STYLE}" "${COLLECTION_PATH}/cr_objects.txt"

	namespace=$(get_namespace "${operator_short_name}")
	if [[ $namespace != "" ]]; then

		show_header "${title} pod deployment. namespace ${namespace}"
		run_command "${CMD} describe deployment ${operator_short_name} -n ${namespace}" "${COLLECTION_PATH}/deployment.txt"

		show_header "${title} pod logs"

		sel="name=${operator_short_name}"
		PODS=$(${CMD} get pods --selector=${sel} -n ${namespace})

		show_header "$title running pods"
		echo "$PODS"

		show_header "$title pod logs"
		while read -r line; do
			pod_name=$(echo "$line" | /usr/bin/awk '{ print $1 }')
			run_command "${CMD} logs ${pod_name} -n ${namespace}" "${COLLECTION_PATH}/${pod_name}.log"
		done <<< $(echo "${PODS}" | /usr/bin/sed '1d')
	fi
}

show_operator_info "node-maintenance-operator" "nodemaintenances.nodemaintenance.kubevirt.io"  'node maintenance operator'

